project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://song-bai-gh.github.io/STA9750-2025-SPRING/"
  navbar:
    background: primary
    search: false
    left:
      - text: "Homepage"
        href: "./index.html"
      - text: "MP 01"
        href: "./mp01.html"
    
format:
  html:
    theme: cerulean
    toc: false

editor:
  mode: source
