<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Song Bai">
<meta name="dcterms.date" content="2025-03-16">

<title>Commission to Analyze Taxpayer Spending (CATS) – STA 9750 Submission Material</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-3405eb2cd25431ae6684dd634ade2368.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">
<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="site_libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="site_libs/datatables-binding-0.33/datatables.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">
<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">STA 9750 Submission Material</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="././index.html"> 
<span class="menu-text">Homepage</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="././mp01.html"> 
<span class="menu-text">MP 01</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary"><span class="header-section-number">1</span> Summary</a></li>
  <li><a href="#quick-facts" id="toc-quick-facts" class="nav-link" data-scroll-target="#quick-facts"><span class="header-section-number">2</span> Quick Facts</a></li>
  <li><a href="#general-questions" id="toc-general-questions" class="nav-link" data-scroll-target="#general-questions"><span class="header-section-number">3</span> General Questions</a>
  <ul class="collapse">
  <li><a href="#which-job-title-has-the-highest-base-rate-of-pay-if-needed-assume-a-standard-2000-hour-work-year-and-no-overtime." id="toc-which-job-title-has-the-highest-base-rate-of-pay-if-needed-assume-a-standard-2000-hour-work-year-and-no-overtime." class="nav-link" data-scroll-target="#which-job-title-has-the-highest-base-rate-of-pay-if-needed-assume-a-standard-2000-hour-work-year-and-no-overtime."><span class="header-section-number">3.1</span> Which job title has the highest base rate of pay? (If needed, assume a standard 2000 hour work year and no overtime.)</a></li>
  <li><a href="#which-individual-in-what-year-had-the-single-highest-city-total-payroll-regular-and-overtime-combined" id="toc-which-individual-in-what-year-had-the-single-highest-city-total-payroll-regular-and-overtime-combined" class="nav-link" data-scroll-target="#which-individual-in-what-year-had-the-single-highest-city-total-payroll-regular-and-overtime-combined"><span class="header-section-number">3.2</span> Which individual &amp; in what year had the single highest city total payroll (regular and overtime combined)?</a></li>
  <li><a href="#which-individual-worked-the-most-overtime-hours-in-this-data-set" id="toc-which-individual-worked-the-most-overtime-hours-in-this-data-set" class="nav-link" data-scroll-target="#which-individual-worked-the-most-overtime-hours-in-this-data-set"><span class="header-section-number">3.3</span> Which individual worked the most overtime hours in this data set?</a></li>
  <li><a href="#which-agency-has-the-highest-average-total-annual-payroll-base-and-overtime-pay-per-employee" id="toc-which-agency-has-the-highest-average-total-annual-payroll-base-and-overtime-pay-per-employee" class="nav-link" data-scroll-target="#which-agency-has-the-highest-average-total-annual-payroll-base-and-overtime-pay-per-employee"><span class="header-section-number">3.4</span> Which agency has the highest average total annual payroll (base and overtime pay per employee)?</a></li>
  <li><a href="#which-agency-has-the-most-employees-on-payroll-in-each-year" id="toc-which-agency-has-the-most-employees-on-payroll-in-each-year" class="nav-link" data-scroll-target="#which-agency-has-the-most-employees-on-payroll-in-each-year"><span class="header-section-number">3.5</span> Which agency has the most employees on payroll in each year?</a></li>
  <li><a href="#which-agency-has-the-highest-overtime-usage-compared-to-regular-hours" id="toc-which-agency-has-the-highest-overtime-usage-compared-to-regular-hours" class="nav-link" data-scroll-target="#which-agency-has-the-highest-overtime-usage-compared-to-regular-hours"><span class="header-section-number">3.6</span> Which agency has the highest overtime usage (compared to regular hours)?</a></li>
  <li><a href="#what-is-the-average-salary-of-employees-who-work-outside-the-five-boroughs-that-is-whose-work_location_borough-is-not-one-of-the-five-counties." id="toc-what-is-the-average-salary-of-employees-who-work-outside-the-five-boroughs-that-is-whose-work_location_borough-is-not-one-of-the-five-counties." class="nav-link" data-scroll-target="#what-is-the-average-salary-of-employees-who-work-outside-the-five-boroughs-that-is-whose-work_location_borough-is-not-one-of-the-five-counties."><span class="header-section-number">3.7</span> What is the average salary of employees who work outside the five boroughs? (That is, whose work_location_borough is not one of the five counties.)</a></li>
  <li><a href="#how-much-has-the-citys-aggregate-payroll-grown-over-the-past-10-years" id="toc-how-much-has-the-citys-aggregate-payroll-grown-over-the-past-10-years" class="nav-link" data-scroll-target="#how-much-has-the-citys-aggregate-payroll-grown-over-the-past-10-years"><span class="header-section-number">3.8</span> How much has the city’s aggregate payroll grown over the past 10 years?</a></li>
  </ul></li>
  <li><a href="#policy-i-capping-salaries-at-mayoral-level" id="toc-policy-i-capping-salaries-at-mayoral-level" class="nav-link" data-scroll-target="#policy-i-capping-salaries-at-mayoral-level"><span class="header-section-number">4</span> Policy I: Capping Salaries at Mayoral Level</a></li>
  <li><a href="#policy-ii-increasing-staffing-to-reduce-overtime-expenses" id="toc-policy-ii-increasing-staffing-to-reduce-overtime-expenses" class="nav-link" data-scroll-target="#policy-ii-increasing-staffing-to-reduce-overtime-expenses"><span class="header-section-number">5</span> Policy II: Increasing Staffing to Reduce Overtime Expenses</a></li>
  <li><a href="#policy-iii-remote-working-as-a-citywide-policy" id="toc-policy-iii-remote-working-as-a-citywide-policy" class="nav-link" data-scroll-target="#policy-iii-remote-working-as-a-citywide-policy"><span class="header-section-number">6</span> Policy III: Remote Working as a Citywide Policy</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">7</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Commission to Analyze Taxpayer Spending (CATS)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Song Bai </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 16, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="summary" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Summary</h1>
<p>The New York City’s new Commission to Analyze Taxpayer Spending (CATS) intended to understand the city’s expenses and wondered if there were any opportunities to spend taxpayers’ money more efficiently. As a senior technical analyst, I will help analyze the city payroll and identify the instances where senior agency officials make significantly more than rank-and-file city employees. I will use City payroll data from NYC Open Data and highlight possible savings to be submitted to the commission.</p>
</section>
<section id="quick-facts" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Quick Facts</h1>
<p>Here are some quick facts about city payroll data.</p>
<ul>
<li>Member of civilian complaint review board has the highest base rate of pay.</li>
<li>Gregory Russ had the highest payroll of 414707 in 2020, 2021, and 2022.</li>
<li>James Internicola worked the most overtime hours of 3693.</li>
<li>Office of Racial Equity has the highest average total annual payroll.</li>
<li>Department of Ed Pedagogical has the most employees in every year.</li>
<li>Board of Election has the highest overtime usage.</li>
<li>The average salary of employees working outside the New York City is 55503.</li>
<li>The city’s payroll has grown 13384.23 dollars and 32.29% over the past 10 years. # Data Downloading I started by downloading the city payroll data with the following code (Click “Show the code” to see). This code also created a data file in the directory.</li>
</ul>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">file.exists</span>(<span class="st">"data/mp01/nyc_payroll_export.csv"</span>)){</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">dir.create</span>(<span class="st">"data/mp01"</span>, <span class="at">showWarnings=</span><span class="cn">FALSE</span>, <span class="at">recursive=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  ENDPOINT <span class="ot">&lt;-</span> <span class="st">"https://data.cityofnewyork.us/resource/k397-673e.json"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"httr2"</span>)) <span class="fu">install.packages</span>(<span class="st">"httr2"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(httr2)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"jsonlite"</span>)) <span class="fu">install.packages</span>(<span class="st">"jsonlite"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(jsonlite)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"dplyr"</span>)) <span class="fu">install.packages</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(dplyr)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"readr"</span>)) <span class="fu">install.packages</span>(<span class="st">"readr"</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(readr)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>  BATCH_SIZE <span class="ot">&lt;-</span> <span class="dv">50000</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  OFFSET     <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>  END_OF_EXPORT <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>  ALL_DATA <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>  <span class="cf">while</span>(<span class="sc">!</span>END_OF_EXPORT){</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    <span class="fu">cat</span>(<span class="st">"Requesting items"</span>, OFFSET, <span class="st">"to"</span>, BATCH_SIZE <span class="sc">+</span> OFFSET, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    req <span class="ot">&lt;-</span> <span class="fu">request</span>(ENDPOINT) <span class="sc">|&gt;</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>      <span class="fu">req_url_query</span>(<span class="st">`</span><span class="at">$limit</span><span class="st">`</span>  <span class="ot">=</span> BATCH_SIZE, </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>                    <span class="st">`</span><span class="at">$offset</span><span class="st">`</span> <span class="ot">=</span> OFFSET)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    resp <span class="ot">&lt;-</span> <span class="fu">req_perform</span>(req)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>    batch_data <span class="ot">&lt;-</span> <span class="fu">fromJSON</span>(<span class="fu">resp_body_string</span>(resp))</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    ALL_DATA <span class="ot">&lt;-</span> <span class="fu">c</span>(ALL_DATA, <span class="fu">list</span>(batch_data))</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(<span class="fu">NROW</span>(batch_data) <span class="sc">!=</span> BATCH_SIZE){</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>      END_OF_EXPORT <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>      <span class="fu">cat</span>(<span class="st">"End of Data Export Reached</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>      OFFSET <span class="ot">&lt;-</span> OFFSET <span class="sc">+</span> BATCH_SIZE</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>  ALL_DATA <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(ALL_DATA)</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cat</span>(<span class="st">"Data export complete:"</span>, <span class="fu">NROW</span>(ALL_DATA), <span class="st">"rows and"</span>, <span class="fu">NCOL</span>(ALL_DATA), <span class="st">"columns."</span>)</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">write_csv</span>(ALL_DATA, <span class="st">"data/mp01/nyc_payroll_export.csv"</span>)</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>After I acquired the latest NYC Payroll Data, I used read_csv function from the readr package to read my data file into R. I made a few changes before my analysis like changing some of the string columns to more conventional punctuation. Specifically, I used a mutate command and the str_to_title from stringr package to convert the following columns’ formatting.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>nyc_payroll <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/mp01/nyc_payroll_export.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>nyc_payroll <span class="ot">&lt;-</span> nyc_payroll <span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">agency_name =</span> <span class="fu">str_to_title</span>(agency_name),</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">last_name =</span> <span class="fu">str_to_title</span>(last_name),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">first_name =</span> <span class="fu">str_to_title</span>(first_name),</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">work_location_borough =</span> <span class="fu">str_to_title</span>(work_location_borough),</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title_description =</span> <span class="fu">str_to_title</span>(title_description),</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">leave_status_as_of_june_30 =</span> <span class="fu">str_to_title</span>(leave_status_as_of_june_30)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Let’s check our data with glimpse function to make sure it is properly formatting.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(nyc_payroll)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 6,225,611
Columns: 17
$ fiscal_year                &lt;dbl&gt; 2024, 2024, 2024, 2024, 2024, 2024, 2024, 2…
$ payroll_number             &lt;dbl&gt; 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67,…
$ agency_name                &lt;chr&gt; "Admin For Children's Svcs", "Admin For Chi…
$ last_name                  &lt;chr&gt; "Faye Fall", "Kilgore", "Wisdom", "Miller",…
$ first_name                 &lt;chr&gt; "Sokhna", "Orlantha", "Cherise", "Moya-Gaye…
$ mid_init                   &lt;chr&gt; "M", "B", "M", "S", "M", "L", "O", NA, "N",…
$ agency_start_date          &lt;dttm&gt; 2023-11-20, 2023-08-28, 2022-10-24, 2023-0…
$ work_location_borough      &lt;chr&gt; "Bronx", "Brooklyn", "Manhattan", "Manhatta…
$ title_description          &lt;chr&gt; "Child Protective Specialist", "Child Prote…
$ leave_status_as_of_june_30 &lt;chr&gt; "Active", "Active", "On Leave", "On Leave",…
$ base_salary                &lt;dbl&gt; 62043, 62043, 43144, 62043, 60236, 62043, 6…
$ pay_basis                  &lt;chr&gt; "per Annum", "per Annum", "per Annum", "per…
$ regular_hours              &lt;dbl&gt; 1050.00, 1470.00, 1251.50, 1400.75, 700.00,…
$ regular_gross_paid         &lt;dbl&gt; 31267.96, 44660.96, 28649.20, 44515.43, 221…
$ ot_hours                   &lt;dbl&gt; 12.00, 99.75, 30.00, 44.75, 53.00, 146.00, …
$ total_ot_paid              &lt;dbl&gt; 425.00, 3859.84, 802.42, 1476.98, 1933.33, …
$ total_other_pay            &lt;dbl&gt; 78.04, 78.14, 78.26, 78.37, 78.47, 78.86, 7…</code></pre>
</div>
</div>
<p>We can see now the formatting of the six columns’ values are well converted. We could also understand what the relevant columns are of the data set by looking at the above output. Next, let’s take a look at the career of the current mayor Eric L. Adams by using the following code to create a table.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>carrer_adams <span class="ot">&lt;-</span> nyc_payroll <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(last_name <span class="sc">==</span> <span class="st">"Adams"</span> <span class="sc">&amp;</span> first_name <span class="sc">==</span> <span class="st">"Eric"</span> <span class="sc">&amp;</span> mid_init <span class="sc">==</span> <span class="st">"L"</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(fiscal_year) <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(fiscal_year,title_description,agency_name,base_salary)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>carrer_adams <span class="ot">&lt;-</span> carrer_adams <span class="sc">|&gt;</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">base_salary =</span> <span class="fu">ifelse</span>(fiscal_year <span class="sc">==</span> <span class="st">"2022"</span><span class="sc">&amp;</span>title_description<span class="sc">==</span><span class="st">"Borough President"</span>, </span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>                              <span class="dv">179200</span><span class="sc">/</span><span class="dv">2</span>, base_salary)) <span class="sc">|&gt;</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">base_salary =</span> <span class="fu">ifelse</span>(fiscal_year <span class="sc">==</span> <span class="st">"2022"</span><span class="sc">&amp;</span>title_description<span class="sc">==</span><span class="st">"Mayor"</span>, </span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>                              <span class="dv">258750</span><span class="sc">/</span><span class="dv">2</span>, base_salary))</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>carrer_adams <span class="ot">&lt;-</span> carrer_adams <span class="sc">|&gt;</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Fiscal Year'</span> <span class="ot">=</span> fiscal_year,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">Position =</span> title_description,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">Agency =</span> agency_name,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Total Salary'</span> <span class="ot">=</span> base_salary</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DT)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>carrer_adams <span class="sc">|&gt;</span> </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="st">`</span><span class="at">Total Salary</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">dollar</span>(<span class="st">`</span><span class="at">Total Salary</span><span class="st">`</span>)) <span class="sc">|&gt;</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">datatable</span>(<span class="at">options=</span><span class="fu">list</span>(<span class="at">searching=</span><span class="cn">FALSE</span>, </span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">paging=</span><span class="cn">FALSE</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">info=</span><span class="cn">FALSE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="datatables html-widget html-fill-item" id="htmlwidget-99f92c77bb03f9d97ae1" style="width:100%;height:auto;"></div>
<script type="application/json" data-for="htmlwidget-99f92c77bb03f9d97ae1">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10","11","12"],[2014,2015,2016,2017,2018,2019,2020,2021,2022,2022,2023,2024],["Borough President","Borough President","Borough President","Borough President","Borough President","Borough President","Borough President","Borough President","Borough President","Mayor","Mayor","Mayor"],["Borough President-Brooklyn","Borough President-Brooklyn","Borough President-Brooklyn","Borough President-Brooklyn","Borough President-Brooklyn","Borough President-Brooklyn","Borough President-Brooklyn","Borough President-Brooklyn","Borough President-Brooklyn","Office Of The Mayor","Office Of The Mayor","Office Of The Mayor"],["$160,000","$160,000","$179,200","$179,200","$179,200","$179,200","$179,200","$179,200","$89,600","$129,375","$258,750","$258,750"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Fiscal Year<\/th>\n      <th>Position<\/th>\n      <th>Agency<\/th>\n      <th>Total Salary<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"searching":false,"paging":false,"info":false,"columnDefs":[{"className":"dt-right","targets":1},{"orderable":false,"targets":0},{"name":" ","targets":0},{"name":"Fiscal Year","targets":1},{"name":"Position","targets":2},{"name":"Agency","targets":3},{"name":"Total Salary","targets":4}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Because the Mayoral term does not line up with the fiscal year, we can see from the table that in 2022, Mr.&nbsp;Adams held two jobs as Borough President and Mayor. I calculated his total salary in that year as the average of total salaries for Borough President and Mayor. I used the DT package to create a better visualization of the employee salary table for Mr.&nbsp;Adams.</p>
<p>After that, I wanted to compute actual total compensation for each employee in our data set. I took a look at the different pay structures by using the following code.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(nyc_payroll<span class="sc">$</span>pay_basis)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "per Annum"       "per Hour"        "per Day"         "Prorated Annual"</code></pre>
</div>
</div>
<p>We can see employees are paid hourly, daily, annually or other way. Thus, I used a case_when function inside a mutate command to handle this.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>total_compensation <span class="ot">&lt;-</span> nyc_payroll <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">total_compensation =</span> <span class="fu">case_when</span>(</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>      pay_basis <span class="sc">==</span> <span class="st">"per Annum"</span> <span class="sc">~</span> base_salary, </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>      pay_basis <span class="sc">==</span> <span class="st">"per Hour"</span> <span class="sc">~</span> base_salary <span class="sc">*</span> (regular_hours<span class="fl">+1.5</span><span class="sc">*</span> ot_hours),</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>      pay_basis <span class="sc">==</span> <span class="st">"per Day"</span> <span class="sc">~</span> base_salary <span class="sc">*</span> (regular_hours<span class="sc">+</span>ot_hours)<span class="sc">/</span><span class="fl">7.5</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span>  </span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="general-questions" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> General Questions</h1>
<p>Now that we have computed total compensation for each city employee, we can go forward to analyze the city payroll. Let’s begin by answering some general questions about the data set.</p>
<section id="which-job-title-has-the-highest-base-rate-of-pay-if-needed-assume-a-standard-2000-hour-work-year-and-no-overtime." class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="which-job-title-has-the-highest-base-rate-of-pay-if-needed-assume-a-standard-2000-hour-work-year-and-no-overtime."><span class="header-section-number">3.1</span> Which job title has the highest base rate of pay? (If needed, assume a standard 2000 hour work year and no overtime.)</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>total_compensation <span class="sc">|&gt;</span> <span class="fu">mutate</span>(</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">base_rate =</span> <span class="fu">case_when</span>(</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    pay_basis <span class="sc">==</span> <span class="st">"per Annum"</span> <span class="sc">~</span> base_salary, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    pay_basis <span class="sc">==</span> <span class="st">"per Hour"</span> <span class="sc">~</span> base_salary <span class="sc">*</span> <span class="dv">2000</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    pay_basis <span class="sc">==</span> <span class="st">"per Day"</span> <span class="sc">~</span> base_salary <span class="sc">*</span> <span class="dv">2000</span><span class="sc">/</span><span class="fl">7.5</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span>  </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> <span class="fu">group_by</span>(title_description) <span class="sc">|&gt;</span> <span class="fu">summarize</span>(<span class="at">mean_rate=</span><span class="fu">mean</span>(base_rate)) <span class="sc">|&gt;</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean_rate))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,977 × 2
   title_description                                 mean_rate
   &lt;chr&gt;                                                 &lt;dbl&gt;
 1 Custodian Engineer                               120870091.
 2 Member, Civilian Complaint Review Board             639785.
 3 Medical Investigator                                623926.
 4 Chairman                                            379618.
 5 Member Of The Environmental Control Board - Oath    350188.
 6 Chief Actuary                                       296470.
 7 Pension Investment Advisor                          295814.
 8 Chancellor                                          287066.
 9 Captain - Chief Of Staff                            276588 
10 First Deputy Mayor                                  274919.
# ℹ 1,967 more rows</code></pre>
</div>
</div>
<p>We can see the list of job titles with the highest base rate of pay. But the first title seems an outlier, I would say the member of civilian complaint review board has the highest base rate of pay.</p>
</section>
<section id="which-individual-in-what-year-had-the-single-highest-city-total-payroll-regular-and-overtime-combined" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="which-individual-in-what-year-had-the-single-highest-city-total-payroll-regular-and-overtime-combined"><span class="header-section-number">3.2</span> Which individual &amp; in what year had the single highest city total payroll (regular and overtime combined)?</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>total_compensation <span class="sc">|&gt;</span> </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(fiscal_year,first_name,last_name,total_compensation) <span class="sc">|&gt;</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_compensation))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6,225,611 × 4
   fiscal_year first_name last_name   total_compensation
         &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;                    &lt;dbl&gt;
 1        2022 Gregory    Russ                    414707
 2        2021 Gregory    Russ                    414707
 3        2020 Gregory    Russ                    414707
 4        2024 Lisa       Bova-Hiatt              393532
 5        2024 Steven     Meier                   373320
 6        2023 David      Banks                   363346
 7        2023 David      Banks                   363346
 8        2022 David      Banks                   363346
 9        2022 Meisha     Ross Porter             363346
10        2021 Meisha     Ross Porter             363346
# ℹ 6,225,601 more rows</code></pre>
</div>
</div>
<p>We can see Gregory Russ had the highest payroll of 414707 in 2020, 2021, and 2022.</p>
</section>
<section id="which-individual-worked-the-most-overtime-hours-in-this-data-set" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="which-individual-worked-the-most-overtime-hours-in-this-data-set"><span class="header-section-number">3.3</span> Which individual worked the most overtime hours in this data set?</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>total_compensation <span class="sc">|&gt;</span> <span class="fu">summarize</span>(fiscal_year,first_name,last_name,ot_hours) <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(ot_hours))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6,225,611 × 4
   fiscal_year first_name last_name   ot_hours
         &lt;dbl&gt; &lt;chr&gt;      &lt;chr&gt;          &lt;dbl&gt;
 1        2022 James      Internicola    3693.
 2        2022 Michael    Thompson       3618.
 3        2022 Timothy    Sands          3556.
 4        2014 John       Murphy         3348.
 5        2022 Seeta      Deochan        3341.
 6        2022 Dion       Middleton      3328.
 7        2024 Kashwayne  Burnett        3303.
 8        2022 Anthony    Messam         3271 
 9        2022 Davey      Payne          3241 
10        2022 Andre      Boucaud        3214 
# ℹ 6,225,601 more rows</code></pre>
</div>
</div>
<p>James Internicola worked the most overtime hours of 3693.</p>
</section>
<section id="which-agency-has-the-highest-average-total-annual-payroll-base-and-overtime-pay-per-employee" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="which-agency-has-the-highest-average-total-annual-payroll-base-and-overtime-pay-per-employee"><span class="header-section-number">3.4</span> Which agency has the highest average total annual payroll (base and overtime pay per employee)?</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>total_compensation <span class="sc">|&gt;</span> <span class="fu">group_by</span>(agency_name) <span class="sc">|&gt;</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_tot_pay=</span><span class="fu">mean</span>(total_compensation)) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(avg_tot_pay))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 169 × 2
   agency_name                    avg_tot_pay
   &lt;chr&gt;                                &lt;dbl&gt;
 1 Office Of Racial Equity            151093.
 2 Commission On Racial Equity        136191 
 3 Districting Commission             120641.
 4 Office Of Criminal Justice         117280.
 5 Office Of Collective Bargainin     114884.
 6 Financial Info Svcs Agency         111230.
 7 Office Of The Actuary              106924.
 8 Bronx Community Board #3           105814.
 9 Public Administrator-Richmond      105752.
10 Municipal Water Fin Authority      101300.
# ℹ 159 more rows</code></pre>
</div>
</div>
<p>Office of Racial Equity has the highest average total annual payroll.</p>
</section>
<section id="which-agency-has-the-most-employees-on-payroll-in-each-year" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="which-agency-has-the-most-employees-on-payroll-in-each-year"><span class="header-section-number">3.5</span> Which agency has the most employees on payroll in each year?</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>total_compensation <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fiscal_year, agency_name) <span class="sc">|&gt;</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">num_empl=</span><span class="fu">n</span>(),<span class="at">.groups=</span><span class="st">"drop"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fiscal_year) <span class="sc">|&gt;</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_max</span>(num_empl,<span class="at">n=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 3
# Groups:   fiscal_year [11]
   fiscal_year agency_name            num_empl
         &lt;dbl&gt; &lt;chr&gt;                     &lt;int&gt;
 1        2014 Dept Of Ed Pedagogical   100589
 2        2015 Dept Of Ed Pedagogical   111857
 3        2016 Dept Of Ed Pedagogical   106263
 4        2017 Dept Of Ed Pedagogical   104629
 5        2018 Dept Of Ed Pedagogical   107956
 6        2019 Dept Of Ed Pedagogical   112067
 7        2020 Dept Of Ed Pedagogical   114999
 8        2021 Dept Of Ed Pedagogical   113523
 9        2022 Dept Of Ed Pedagogical   120453
10        2023 Dept Of Ed Pedagogical   106882
11        2024 Dept Of Ed Pedagogical   108209</code></pre>
</div>
</div>
<p>Department of Ed Pedagogical has the most employees in every year.</p>
</section>
<section id="which-agency-has-the-highest-overtime-usage-compared-to-regular-hours" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="which-agency-has-the-highest-overtime-usage-compared-to-regular-hours"><span class="header-section-number">3.6</span> Which agency has the highest overtime usage (compared to regular hours)?</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>total_compensation <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(agency_name) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">ot_usage=</span><span class="fu">mean</span>(ot_hours)<span class="sc">/</span><span class="fu">mean</span>(regular_hours)) <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(ot_usage))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 169 × 2
   agency_name                  ot_usage
   &lt;chr&gt;                           &lt;dbl&gt;
 1 Board Of Election              0.200 
 2 Fire Department                0.190 
 3 Department Of Correction       0.185 
 4 Department Of Sanitation       0.138 
 5 Police Department              0.125 
 6 Dept Of Citywide Admin Svcs    0.120 
 7 Department Of Transportation   0.115 
 8 Dept. Of Homeless Services     0.109 
 9 Nyc Housing Authority          0.106 
10 Admin For Children's Svcs      0.0812
# ℹ 159 more rows</code></pre>
</div>
</div>
<p>Board of Election has the highest overtime usage.</p>
</section>
<section id="what-is-the-average-salary-of-employees-who-work-outside-the-five-boroughs-that-is-whose-work_location_borough-is-not-one-of-the-five-counties." class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="what-is-the-average-salary-of-employees-who-work-outside-the-five-boroughs-that-is-whose-work_location_borough-is-not-one-of-the-five-counties."><span class="header-section-number">3.7</span> What is the average salary of employees who work outside the five boroughs? (That is, whose work_location_borough is not one of the five counties.)</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>total_compensation <span class="sc">|&gt;</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span>work_location_borough <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Manhattan"</span>, <span class="st">"Brooklyn"</span>, <span class="st">"Queens"</span>, </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>                                     <span class="st">"Bronx"</span>, <span class="st">"Richmond"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_salary=</span><span class="fu">mean</span>(total_compensation,<span class="at">na.rm=</span><span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  avg_salary
       &lt;dbl&gt;
1     55503.</code></pre>
</div>
</div>
<p>The average salary of employees working outside the New York City is 55503.</p>
</section>
<section id="how-much-has-the-citys-aggregate-payroll-grown-over-the-past-10-years" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="how-much-has-the-citys-aggregate-payroll-grown-over-the-past-10-years"><span class="header-section-number">3.8</span> How much has the city’s aggregate payroll grown over the past 10 years?</h2>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>growth <span class="ot">&lt;-</span> total_compensation <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fiscal_year) <span class="sc">|&gt;</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">agg_pay=</span><span class="fu">mean</span>(total_compensation,<span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>agg_pay_2024 <span class="ot">&lt;-</span> growth <span class="sc">|&gt;</span> <span class="fu">filter</span>(fiscal_year<span class="sc">==</span><span class="st">"2024"</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(agg_pay)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>agg_pay_2014 <span class="ot">&lt;-</span> growth <span class="sc">|&gt;</span> <span class="fu">filter</span>(fiscal_year<span class="sc">==</span><span class="st">"2014"</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(agg_pay)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>growth_amount <span class="ot">&lt;-</span> agg_pay_2024 <span class="sc">-</span> agg_pay_2014</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>growth_percentage <span class="ot">&lt;-</span> growth_amount<span class="sc">/</span>agg_pay_2014<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>growth_amount</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 13384.23</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>growth_percentage</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32.2868</code></pre>
</div>
</div>
<p>The city’s payroll has grown 13384.23 dollars and 32.29% over the past 10 years.</p>
<p>Now, I will analyze three possible policy changes to see their impact on overall spending. I have two policies suggested and will come up with my own policy proposal for analysis. For each policy, I will i) compute its impact on city payroll, ii) determine any other staffing adjustments required, and iii) make a recommendation to the CATS.</p>
</section>
</section>
<section id="policy-i-capping-salaries-at-mayoral-level" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Policy I: Capping Salaries at Mayoral Level</h1>
<p>We are interested in finding out employees making more than the mayor in each fiscal year. I first computed the total mayor pay for each fiscal year, and then identify employees who made more than this amount in the same fiscal year.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>mayor_pay_per_year <span class="ot">&lt;-</span> total_compensation <span class="sc">|&gt;</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(title_description <span class="sc">==</span> <span class="st">"Mayor"</span>) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fiscal_year) <span class="sc">|&gt;</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">mayor_pay =</span> <span class="fu">mean</span>(total_compensation))</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>employees_above_mayor <span class="ot">&lt;-</span> total_compensation <span class="sc">|&gt;</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(mayor_pay_per_year, <span class="at">by =</span> <span class="st">"fiscal_year"</span>) <span class="sc">|&gt;</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(total_compensation <span class="sc">&gt;</span> mayor_pay)</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>mayor_pay_per_year</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 11 × 2
   fiscal_year mayor_pay
         &lt;dbl&gt;     &lt;dbl&gt;
 1        2014   112500.
 2        2015   225000 
 3        2016   225000 
 4        2017   225000 
 5        2018   258750 
 6        2019   258750 
 7        2020   258750 
 8        2021   258750 
 9        2022   258750 
10        2023   258750 
11        2024   258750 </code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>employees_above_mayor</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 14,076 × 19
   fiscal_year payroll_number agency_name          last_name first_name mid_init
         &lt;dbl&gt;          &lt;dbl&gt; &lt;chr&gt;                &lt;chr&gt;     &lt;chr&gt;      &lt;chr&gt;   
 1        2024             67 Admin For Children'… Cleary    Joan       M       
 2        2024             67 Admin For Children'… Pletniko… Margaret   &lt;NA&gt;    
 3        2024             67 Admin For Children'… Hines-Jo… Lisa       C       
 4        2024             67 Admin For Children'… Gendell   Stephanie  J       
 5        2024             67 Admin For Children'… White     Andrew     K       
 6        2024             67 Admin For Children'… Mendoza   Angel      V       
 7        2024             67 Admin For Children'… Dannhaus… Jess       B       
 8        2024             67 Admin For Children'… Wolkomir  Elizabeth  D       
 9        2024             67 Admin For Children'… Sputz     Alan       W       
10        2024             67 Admin For Children'… Saunders  Winette    &lt;NA&gt;    
# ℹ 14,066 more rows
# ℹ 13 more variables: agency_start_date &lt;dttm&gt;, work_location_borough &lt;chr&gt;,
#   title_description &lt;chr&gt;, leave_status_as_of_june_30 &lt;chr&gt;,
#   base_salary &lt;dbl&gt;, pay_basis &lt;chr&gt;, regular_hours &lt;dbl&gt;,
#   regular_gross_paid &lt;dbl&gt;, ot_hours &lt;dbl&gt;, total_ot_paid &lt;dbl&gt;,
#   total_other_pay &lt;dbl&gt;, total_compensation &lt;dbl&gt;, mayor_pay &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Next, we want to know how much would be saved if these employees’ salary were capped at the mayor’s level.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>employees_above_mayor <span class="ot">&lt;-</span> employees_above_mayor <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">savings =</span> total_compensation <span class="sc">-</span> mayor_pay)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>total_savings <span class="ot">&lt;-</span> <span class="fu">sum</span>(employees_above_mayor<span class="sc">$</span>savings)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>total_savings</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 272525990</code></pre>
</div>
</div>
<p>It looks like a large amount of money. We would also want to know if this policy was adopted, which agencies and job titles would bear the most. We do this by calculating the average savings in each combination of agencies and job titles and sorting them to see the top ones.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>savings_by_agency_and_title <span class="ot">&lt;-</span> employees_above_mayor <span class="sc">|&gt;</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(fiscal_year<span class="sc">&gt;</span><span class="st">"2014"</span>) <span class="sc">|&gt;</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(agency_name,title_description ) <span class="sc">|&gt;</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_savings =</span> <span class="fu">mean</span>(savings)) <span class="sc">|&gt;</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(avg_savings))</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>savings_by_agency_and_title</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 208 × 3
# Groups:   agency_name [67]
   agency_name                   title_description            avg_savings
   &lt;chr&gt;                         &lt;chr&gt;                              &lt;dbl&gt;
 1 Nyc Housing Authority         Chair                            118639.
 2 Dept Of Ed Pedagogical        Assistant Superintendent         104596 
 3 Office Of The Comptroller     Pension Investment Advisor        91686 
 4 Dept Of Ed Pedagogical        Chancellor                        79505.
 5 Nyc Housing Authority         Executive Agency Counsel          67985.
 6 Office Of The Actuary         Chief Actuary                     53196.
 7 Office Of The Actuary         Administrative Actuary            53135 
 8 Office Of The Comptroller     Administrative Staff Analyst      41667.
 9 Community College (Bronx)     President                         36136 
10 Dept Of Health/Mental Hygiene City Medical Specialist           35156.
# ℹ 198 more rows</code></pre>
</div>
</div>
<p>The Chair of NYC Housing Authority would bear the brunt of this policy with an average savings of 118639. If this policy was adopted, around 273 million would be saved each year. We would not need to hire more employees to implement that policy. It is almost the easiest way to save the money and would not bring too much negative impact to the city. I would recommend to the CATS that this policy should be adopted to generate more than 200 millions of dollars every year which can be used to bring more benifits to the city.</p>
</section>
<section id="policy-ii-increasing-staffing-to-reduce-overtime-expenses" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Policy II: Increasing Staffing to Reduce Overtime Expenses</h1>
<p>There are some potential upsides of increasing employment to reduce overtime cost. Let’s first find out how many overtime hours worked for each combination of agency and job title. Then we estimate the number of new full-time employees needed to replace that much overtime. I did the job using the following code.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>overtime_by_agency_and_title <span class="ot">&lt;-</span> total_compensation <span class="sc">|&gt;</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(agency_name , title_description) <span class="sc">|&gt;</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total_overtime_hours =</span> <span class="fu">sum</span>(ot_hours)) <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_overtime_hours))</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>overtime_with_ft_equivalents <span class="ot">&lt;-</span> overtime_by_agency_and_title <span class="sc">|&gt;</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">full_time_equivalents =</span> total_overtime_hours <span class="sc">/</span> <span class="dv">2000</span>)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>overtime_by_agency_and_title</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8,351 × 3
# Groups:   agency_name [169]
   agency_name              title_description         total_overtime_hours
   &lt;chr&gt;                    &lt;chr&gt;                                    &lt;dbl&gt;
 1 Police Department        Police Officer                       58898639.
 2 Fire Department          Firefighter                          43536213.
 3 Department Of Correction Correction Officer                   34092745.
 4 Department Of Sanitation Sanitation Worker                    23098266.
 5 Police Department        P.o. Da Det Gr3                      15314153.
 6 Police Department        School Safety Agent                  14967018.
 7 Nyc Housing Authority    Caretaker                             9439229.
 8 Police Department        Sergeant-                             8424793.
 9 Fire Department          Lieutenant                            7607797.
10 Police Department        Traffic Enforcement Agent             7003213.
# ℹ 8,341 more rows</code></pre>
</div>
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>overtime_with_ft_equivalents</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8,351 × 4
# Groups:   agency_name [169]
   agency_name      title_description total_overtime_hours full_time_equivalents
   &lt;chr&gt;            &lt;chr&gt;                            &lt;dbl&gt;                 &lt;dbl&gt;
 1 Police Departme… Police Officer               58898639.                29449.
 2 Fire Department  Firefighter                  43536213.                21768.
 3 Department Of C… Correction Offic…            34092745.                17046.
 4 Department Of S… Sanitation Worker            23098266.                11549.
 5 Police Departme… P.o. Da Det Gr3              15314153.                 7657.
 6 Police Departme… School Safety Ag…            14967018.                 7484.
 7 Nyc Housing Aut… Caretaker                     9439229.                 4720.
 8 Police Departme… Sergeant-                     8424793.                 4212.
 9 Fire Department  Lieutenant                    7607797.                 3804.
10 Police Departme… Traffic Enforcem…             7003213.                 3502.
# ℹ 8,341 more rows</code></pre>
</div>
</div>
<p>Then, we will see how much money could be saved if we replaced the overtime working with regular time working from new employees.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>base_rate <span class="ot">&lt;-</span> total_compensation <span class="sc">|&gt;</span> <span class="fu">mutate</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">base_rate =</span> <span class="fu">case_when</span>(</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>    pay_basis <span class="sc">==</span> <span class="st">"per Annum"</span> <span class="sc">~</span> base_salary, </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>    pay_basis <span class="sc">==</span> <span class="st">"per Hour"</span> <span class="sc">~</span> base_salary <span class="sc">*</span> <span class="dv">2000</span>,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>    pay_basis <span class="sc">==</span> <span class="st">"per Day"</span> <span class="sc">~</span> base_salary <span class="sc">*</span> <span class="dv">2000</span><span class="sc">/</span><span class="fl">7.5</span>,</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="cn">NA_real_</span>  </span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>overtime_by_agency_and_title <span class="ot">&lt;-</span> base_rate <span class="sc">|&gt;</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(agency_name, title_description) <span class="sc">|&gt;</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total_overtime_hours =</span> <span class="fu">sum</span>(ot_hours), </span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_regular_salary =</span> <span class="fu">mean</span>(base_rate)) <span class="sc">|&gt;</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_overtime_hours)) </span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>overtime_by_agency_and_title <span class="ot">&lt;-</span> overtime_by_agency_and_title <span class="sc">|&gt;</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">overtime_cost =</span> total_overtime_hours <span class="sc">*</span> <span class="fl">1.5</span> <span class="sc">*</span> avg_regular_salary <span class="sc">/</span> <span class="dv">2000</span>)</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a>savings_by_agency_and_title <span class="ot">&lt;-</span> overtime_by_agency_and_title <span class="sc">|&gt;</span></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">savings =</span> overtime_cost <span class="sc">-</span> (total_overtime_hours <span class="sc">*</span> avg_regular_salary <span class="sc">/</span> <span class="dv">2000</span>)) </span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>savings_by_agency_and_title <span class="sc">|&gt;</span></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(agency_name,title_description,savings) <span class="sc">|&gt;</span></span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(savings))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8,351 × 3
# Groups:   agency_name [169]
   agency_name              title_description                       savings
   &lt;chr&gt;                    &lt;chr&gt;                                     &lt;dbl&gt;
 1 Police Department        Police Officer                      1040781034.
 2 Fire Department          Firefighter                          836859022.
 3 Department Of Correction Correction Officer                   613245406.
 4 Department Of Sanitation Sanitation Worker                    402214527.
 5 Police Department        P.o. Da Det Gr3                      372704345.
 6 Police Department        Sergeant-                            225040284.
 7 Fire Department          Lieutenant                           198745275.
 8 Police Department        School Safety Agent                  157464286.
 9 Police Department        Lieutenant                           146861382.
10 Police Department        Police Officer D/A Detective 2nd Gr  123805712.
# ℹ 8,341 more rows</code></pre>
</div>
</div>
<p>Next, let’s determine the aggregate savings possible by agency using the following code.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>aggregate_savings_by_agency <span class="ot">&lt;-</span> savings_by_agency_and_title <span class="sc">|&gt;</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(agency_name) <span class="sc">|&gt;</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total_savings =</span> <span class="fu">sum</span>(savings)) <span class="sc">|&gt;</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(total_savings))</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>aggregate_savings_by_agency</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 169 × 2
   agency_name                    total_savings
   &lt;chr&gt;                                  &lt;dbl&gt;
 1 Department Of Correction          824929213.
 2 Admin For Children's Svcs         157231704.
 3 Board Of Election                  37477300.
 4 Department Of Buildings            29617709.
 5 Dept. Of Design &amp; Construction      9009313.
 6 District Attorney-Manhattan         8708231.
 7 Community College (Manhattan)       7470882.
 8 Nyc Employees Retirement Sys        6808228.
 9 Law Department                      6267436.
10 Community College (Queensboro)      4879669.
# ℹ 159 more rows</code></pre>
</div>
</div>
<p>The total potencial savings for this policy for each combination of agency and job title is shown above. Around 1 billion dollars could be saved for Police officers in Police Dapartment.The total number of new employees needed would be 29449 for the same job. The police officers in police departments would be affected the most with this new policy. On agency level, Department of Correction would face the largest impact.</p>
<p>I would recommend this policy to the CATS, especially to hire more new full time employees as police officers in Police Department because this would help save more than 1 billion dollars every year and also reduce the police officers’ pressure. On agency level, department of correction should absolutely adopt this policy because they could save far more than any other agencies in the city.</p>
</section>
<section id="policy-iii-remote-working-as-a-citywide-policy" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Policy III: Remote Working as a Citywide Policy</h1>
<p>I want to introduce a citywide remote working policy for all eligible employees in the city. This could help reduce costs like spending for office space and equipment. Let’s consider if half of the total employees in our data set could work remotely and 1% of their total compensation could be saved due to this policy. How much money could be saved annually.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>total_compensation <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">remote_savings=</span><span class="fu">sum</span>(total_compensation,<span class="at">na.rm=</span><span class="cn">TRUE</span>)<span class="sc">*</span><span class="fl">0.5</span><span class="sc">*</span><span class="fl">0.01</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  remote_savings
           &lt;dbl&gt;
1    1483791723.</code></pre>
</div>
</div>
<p>Nearly 1.5 billion dollars could be saved for the city. If this policy was adopted, the time employees spend on commute would also be saved. We assume half an hour of the saved time could convert same amount of time from overtime to regular time per day. I want to know how much money could be saved.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>base_rate <span class="sc">|&gt;</span> </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">ot_to_regular_savings=</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">sum</span>(base_rate<span class="sc">/</span><span class="dv">2000</span><span class="sc">*</span><span class="fl">0.5</span><span class="sc">*</span><span class="fl">0.5</span>,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  ot_to_regular_savings
                  &lt;dbl&gt;
1            250690543.</code></pre>
</div>
</div>
<p>The third policy would have reduced the total payroll expenses by 1.5 billion directly and 250 million with overtime hours converted to regular hours. To implement this policy, no more hiring are required. I recommended this policy to the CATS since it would not only reduce the payroll expenses but also provide more time to employees, which could help improve the productivity.</p>
<p>However, I made some assumptions for the this policy like half of all employees could be working remotely and 1% of their total compensation would be saved following this policy. These might introduce error into my projections because I have not done enough research about how many employees could be remote workers or the proportion of their total salary that could be saved when this policy adopted.</p>
</section>
<section id="conclusion" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusion</h1>
<p>The above three policies could all work to help the Commission of Analyze Taxpayer Spending change how they spend taxpayers’ money and make the process more efficient. The amount of money saved by adopting different policies ranges from hundreds of millions to billions per year. Each of them has different concertations like the combinations of agency and job title. The CATS could combine the three policies or adopt one policy in specific areas.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/song-bai-gh\.github\.io\/STA9750-2025-SPRING\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>